### ISSUE TITLE
Wrong files displayed when browsing quickly

### ISSUE THREAD

**Issue by tkzv** [nomacs/nomacs#1001]
**Describe the bug**
When I browse a directory by pressing and holding an arrow, sometimes images are displayed in wrong order: an image appears only briefly and is replaced by a previous one. For example, the folder has images from 1.png to 1000.png; I start at 1, Nomacs correctly displays 1, 2, 3, 4, briefly shows 5, then quickly replaces it with 4, then displays 6, briefly displays 7, returns to 6, displays 8, 9, 10... This displaying next file and reverting to previous one also creates unpleasant flickering. Meanwhile, the names in the title bar are incremented correctly, so, when the titlebar says "5.png" Nomacs displays 4.png.

This is rather unpredictable — there is no way to tell which files will be displayed and which will be rolled back this particular time. The problem is more likely to manifest when large images are displayed scaled down and/or when there are other processes heavily loading the hard drive and the CPU. I've encountered it for various file types: JPEG, PNG, WebP.

The problem also may manifest when browsing files by pressing (rather than holding) an arrow for each image, if you press it quickly.

Not reproduced when "Image Loading Policy" is "Skip Images".

**To Reproduce**
1. Create a series of large images with numbers. For example, in Linux:
```
for n in `seq -w 1 1000`; do magick -size 10000x5000 label:$n text-$n.webp; done
```
(requires bash, coreutils and ImageMagick)

2. Open "text-0001.webp" in Nomacs. Zoom out to something like 6%.

3. Press and hold right arrow. The displayed numbers would change something like this:
0001
0002
0003 (very briefly)
0002
0004
0005 (very briefly)
0004
0006
0007 (very briefly)
0006
0008
...

**Expected behavior**
The images should be displayed in their correct order: 0001, 0002, 0003, 0004, 0005, 0006, 0007, 0008...

**Screenshots**
Example of browsing:
[obs-capture.zip](https://github.com/nomacs/nomacs/files/13256994/obs-capture.zip)

**Desktop:**
 - OS: Gentoo Linux
 - Versions: kernel: 5.15.32-r1, dev-qt/qtcore-5.15.10-r2, x11-base/xorg-server-21.1.9, media-libs/opencv-4.8.0-r1, media-gfx/nomacs-3.16.224-r6

**Comment by olodar** [comment]
I wondering how they still not care about this bug

**Comment by scrubbbbs** [comment]
Can confirm, git master 6dfc779, Linux, X11, qt 5.15.10

Settings:
- Skip Images: off
- Transition:  Appear 0.0s

**Comment by peterfreeth** [comment]
I've had this problem for a couple of years but I like to use nomacs because of the way that it can show exif data alongside the image. nomacs is still the best image viewer for me but this is a real problem.

When viewing a number of jpeg files in a folder and using either the keyboard left and right arrow keys to move forwards and backwards through the list of images or the on screen left and right arrows, every so often, the screen image does not update. The display flashes but stays on the previous image. If I click through very slowly it's OK.

It's simple, I think, than the original description above. Simply open a folder of images and click through them using the screen arrow or keyboard, after only 4 or 5 images the problem occurs.

The image stays the same as the previously viewed image but the title bar shows the correct new image. I use nomacs to cull photos from events and this problem means that if I then delete an image, I'm deleting the wrong one and this is a major problem.

**Comment by scrubbbbs** [comment]
> that if I then delete an image, I'm deleting the wrong one

Thanks, this definitely adds weight to this issue. I was  not aware that the incorrect image or information was displayed, only that it jumped around unpredictably at times.

I am new to the project and haven't studied the image loading logic much, but this is one area I plan to visit.
