### ISSUE TITLE
Start with full screen mode

### ISSUE THREAD

**Issue by mahdishalchian** [nomacs/nomacs#1032]
Hello, I need it to open in full screen mode when I launch Nomacs. and when I press Esc, it closes the app (not to get out of full screen mode).

**Comment by leejuyuu** [comment]
Hello @mahdishalchian, is this issue about not being able to open nomacs in full screen mode, or is it about you cannot exit full screen mode properly?

**Comment by Ohrwerk** [comment]
When I open an image via double-click in Windows Explorer, the image is not opened in full screen mode.
Unfortunately there is no setting to change this.
(You can open images in full screen mode using the CMD with the -f option, but this is not a solution.
Also a manual change in the registry is not possible (to many entries and unsafe) and does not make sense due to the abundance).

If you view an image in full screen mode and press ESC, the program only switches from full screen mode to "Normal" mode.
Exiting / quitting the program by pressing ESC would be very helpful.
There is an option in the settings that allows you to exit NOMACS by pressing ESC, but this does not exit NOMACS from full screen mode, you always have to press ESC twice.

**Comment by leejuyuu** [comment]
@mahdishalchian @Ohrwerk PR #1136 will make nomacs remember the last mode when it closes. So, if you close nomacs in fullscreen mode with `Alt + F4` or custom `File > Exit` keybinding, the next time nomacs will start in fullscreen. You can test the windows build https://ci.appveyor.com/project/novomesk/nomacs/builds/50343050.
