### ISSUE TITLE
make libnomacs-core a private lib

### ISSUE THREAD

**Issue by agaida** [nomacs/nomacs#109]
aka install it to usr/lib/\*/nomacs/libnomacsCore.so.\* instead of usr/lib/\*/libnomacsCore.so.\* - if this would be possible upstream a lot of busy package maintainers would be thankful - esp. myself :P 

Really, libnomacscore3 is a pita to pack, esp the symbols - if libnomacscore would be a private lib used only by nomacs there would be no need to pack it in a extra package (and also don't mess around with symbols)

**Comment by sfiel** [comment]
hi,
if we change the install directory in cmake to lib/nomacs/ then it also affects the installation into the /usr/local . After a "make install" i'm unable to execute nomacs (I also executed ldconfig), because the system is unable to find libnomacs. seems like,ldconfig does not look for libs in /usr/local/lib/nomacs. do you know how to solve this issue? thanks

**Comment by agaida** [comment]
hihihi, diesen Part wollte ich ganz gepflegt auf Euch abwälzen. I will take care of.

**Comment by diemmarkus** [comment]
I guess that's it - right?

**Comment by agaida** [comment]
right, does the trick
