### ISSUE TITLE
File filter: register file type has no effect (Linux)

### ISSUE THREAD

**Issue by AladW** [nomacs/nomacs#11]
Hi,

When "registering" a file type in Edit > Settings > File Filters, I would expect it to change the default application for the current user. In Linux, this is typically done by modifying $HOME/.local/share/applications/mimeapps.list which is used by xdg-open. I can't however see a change, and the default image viewer is unaffected. But perhaps I'm missing something obvious?

nomacs 2.2.0-1
Arch Linux x64

**Comment by sfiel** [comment]
hi,
"registering" a new file type only means that nomacs will accept such files (in the open dialog or via drag&drop). So it is used when nomacs does not support an image format (because we are not able to know every format) we check if one of our loading routines is able to process the file. It was not intended that it is automatically set as default application for this file.

mimeapps.list handles the default programs yes. But there is no "easy" way in c++ or Qt to process this file and we do not want to start parsing and manipulating this file on our own, because the risks would be to high to damage the file and perhaps all default applications are no longer working. Thus, we recommend using the "set default" application of the desktop environment.

Stefan

**Comment by AladW** [comment]
Fair enough. :) Thanks for replying.
