### ISSUE TITLE
Delete to trash

### ISSUE THREAD

**Issue by ghost** [nomacs/nomacs#163]
I can't send files to trash, only permanently delete them. Is this a bug or a feature I should request? I have latest Nomacs via ppa on elementary OS Loki, based on Ubuntu 16.04.
![screenshot from 2017-10-23 20 03 42](https://user-images.githubusercontent.com/28788471/31902452-9866ebd2-b82d-11e7-9e4a-8ae37eae16b5.png)

**Comment by HalfTough** [comment]
Yes, it would be nice to see that option. Especially if it would use different kind of trash depending on DE being used.

**Comment by CreamyCookie** [comment]
I have the same problem. Trash is often in `.local/share/Trash/files/` so maybe you could add an option to specify the trash location and use that path as the default.

**Comment by bjd-pfq** [comment]
All Linux's adhere to the freedesktop Trash spec, so there's no reason not to implement this.

**Comment by CreamyCookie** [comment]
Thanks @diemmarkus for implementing this

**Comment by diemmarkus** [comment]
> All Linux's adhere to the freedesktop Trash spec, so there's no reason not to implement this.

the solution above solves this issue, doesn't it?

**Comment by JakubRimal** [comment]
Pressing the delete key still permanently deletes files (version 3.12). Can you please specify where/how it should be fixed? Thank you!

**Comment by nsfX** [comment]
> Pressing the delete key still permanently deletes files (version 3.12). Can you please specify where/how it should be fixed? Thank you!

In Debian the last version in the repositories is 3.12, but you need at least the version 3.13.0.4428 which has this new feature. You have to build by yourself following the instructions and you will get the last version (today 3.17) wich has the feature to move the files to trash instead of permanently delete files.

**Comment by JakubRimal** [comment]
Thank you, I've installed 3.17 and it works. :) It's a pity that there is such an old version in Linux repos... :(

**Comment by Thulinma** [comment]
My apologies for waking up such an old issue... but if I'm not mistaken, it is now impossible to _not_ move an image to trash.

In addition, it looks like the moving to trash happens through a rename - which does not work across mounts. So if your trash directory is a different mount from the location of the image you're trying to delete, it's impossible to delete it through nomacs at all. Attempting to do so results in an unhelpful error message "Sorry, I could not delete: FILENAME" without further explanation.

I would suggest an extra dialog for this edge case, with something along the lines of "Could not move to trash, do you wish to permanently delete instead?", and make shift+delete (which is currently move-to-trash-without-confirmation-dialog) instead perform a permanent-delete (perhaps with confirmation dialog..?). Shift+delete is a permanent delete in most other applications that I am aware of, so that should match user expectations better as well.

I'm not very familiar with the nomacs codebase, but would be happy to try and whip up a pull request with (some of) these changes, if that would be welcomed. I imagine somebody more familiar with the codebase would be able to do it much faster than me, however.

**Comment by hollysheep** [comment]
This worked on Ubuntu 20.04 (installed nomacs using flatpak) but not on Ubuntu 22.04. I can move files to trash from a mounted HDD but not from /home. The Permissions of nomacs are:

filesystems=home;/media;xdg-config/kdeglobals:ro;host;
