### ISSUE TITLE
threat alert

### ISSUE THREAD

**Issue by dim-d** [nomacs/nomacs#194]
windows 7 - 64bit
In portable installation, renaming the installation folder triggers this alert.
![nomacs38](https://user-images.githubusercontent.com/17293071/36535735-4e37c1d4-17d3-11e8-8fb2-1b7fac646b92.jpg)
![nomacs38_details](https://user-images.githubusercontent.com/17293071/36536213-cbd9ba88-17d4-11e8-8a59-f145d37e8fd8.jpg)

In the alert message the folder appears as "nomacs-3.8.0" but it has been renamed to "nomacs"

**Comment by diemmarkus** [comment]
Hi,

can you check if *Enable LAN Sync* is checked in `Edit > Settings`? Basically, nomacs listens in the LAN (NOTE: not the internet : ) for other nomacs interactions - this is set to port 45454, [see](https://github.com/nomacs/nomacs/blob/0dd188d21633f9bd83ce4f59c6895cd33f3182dd/ImageLounge/src/DkGui/DkNetwork.h#L30):
```
#define local_tcp_port_start 45454
```
By default, LAN Sync is turned off so that security software won't trigger alerts...

cheers,
markus

**Comment by dim-d** [comment]
I think that the focus should be why it triggers when renaming the installation folder.

**Comment by dim-d** [comment]
I think that the focus should be why it triggers when renaming the installation folder.
Settings are the default.

**Comment by diemmarkus** [comment]
you did not start nomacs at the time, the alert was triggered? 
In that case, I would ask ThreatFire (who seem to have pretty bad heuristics : )
