### ISSUE TITLE
tiff file in CMYK colorspace is not display right in nomacs

### ISSUE THREAD

**Issue by jindili** [nomacs/nomacs#204]
tiff file in CMYK colorspace is not display right in nomacs, 
is there some options needs to be configured?

**Comment by diemmarkus** [comment]
hmmm nope. A major problem with CMYK is that nomacs neglects embedded ICC profiles. can you upload a sample image please?

**Comment by jindili** [comment]
loading result compare

![rgb](https://user-images.githubusercontent.com/73845/38454171-55d77220-3a94-11e8-9621-bb6a98932677.jpg)

![cmyk](https://user-images.githubusercontent.com/73845/38454175-62ee28f0-3a94-11e8-959d-8f2c5e22db19.jpg)

original tiff file:
[cmyk.zip](https://github.com/nomacs/nomacs/files/1886292/cmyk.zip)

**Comment by diemmarkus** [comment]
this image has an embedded ICC profile - that's why we cannot display it correctly. 
![img-2018-08-14 16 41 19](https://user-images.githubusercontent.com/4182443/44098614-f0413df8-9fe0-11e8-95c2-afe962624e2d.png)

I will close this issue for now (since we are not able to fix this in the near future) - sorry!
