### ISSUE TITLE
There is only English in the language list

### ISSUE THREAD

**Issue by laichiaheng** [nomacs/nomacs#207]
OS: Antergos (based on Arch)
![deepin _20180401155216](https://user-images.githubusercontent.com/9532105/38171081-bcfec1bc-35c4-11e8-8da1-8fe74febfe97.png)
![deepin _20180401155934](https://user-images.githubusercontent.com/9532105/38171135-b3c9771c-35c5-11e8-9f8c-31c08773f6e8.png)

**Comment by diemmarkus** [comment]
hi,
this seems to be an issue related to packaging (I only test nomacs with ubuntu which features translations). Maybe @dvzrv can help us here

**Comment by dvzrv** [comment]
Hmm, not sure, will have to look at the [build script](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/nomacs). I'm not doing anything fancy there, but if I should, this should probably be mentioned in the README.md.
However, currently I'm unable to rerelease nomacs anyways, because of #203.

**Comment by dvzrv** [comment]
@laichiaheng well, I'll include it in the 3.8.1, once I can successfully build the nomacs-plugins, too.

**Comment by diemmarkus** [comment]
thanks! it is `false` by default, because we want nomacs to be easily built for newbies (some people had issues with translations when building) - but adding it to the `README` is a good idea...

**Comment by dvzrv** [comment]
Fixed in 3.8.1

**Comment by diemmarkus** [comment]
cool, thanks!
