### ISSUE TITLE
German translated text in help view

### ISSUE THREAD

**Issue by ReS1010** [nomacs/nomacs#228]
Your wrote: 
"FLO was here und wünscht Stefan fiel Spaß während Markus rockt..."
should be corrected to: 
"FLO war hier und wünscht Stefan viel Spass, während Markus rockt..."

--> Apart from the fact that this text is completely meaningless and has nothing to do in an "About" View!

Regards.
R.

**Comment by diemmarkus** [comment]
Hi,

indeed, this text is pretty meaningless. But all mistakes are intended, which make nomacs our 'product' and that's why it belongs right where it is. Here are some explanations:
_"[Flo was here](https://scholar.google.at/scholar?hl=en&as_sdt=0%2C5&q=%22flo+was+here%22&btnG=) und wünscht [Stefan fiel](https://nomacs.org/contact/) Spaß während [Markus rockt](https://scholar.google.at/scholar?hl=en&as_sdt=0%2C5&q=%22markus+rockt%22&btnG=)..."_

best,
markus
