### ISSUE TITLE
Locale issues

### ISSUE THREAD

**Issue by Vladimir-csp** [nomacs/nomacs#233]
Hi!
A couple of issues with locales:
1. On first launch Nomacs asks for language selection (with English as default) instead of just using current locale.
2. Date format seems to be hardcoded and not affected by locale:
![image](https://user-images.githubusercontent.com/4061903/42754128-f600c25a-88fb-11e8-869b-df5d7256a832.png)

**Comment by diemmarkus** [comment]
Hi,

thanks for your feedback.
@1. on the first start-up we ask users to choose their language because we don't know (and can't check : ) the quality of community based translations.
@2. we use Qt's locale settings which works on most systems:
![img-2018-08-06 09 18 07](https://user-images.githubusercontent.com/4182443/43702993-c49b23fc-995b-11e8-926b-6e7c1ac782d0.png)

best,
markus
