### ISSUE TITLE
Request: display folder images count and image size in the title bar

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [nomacs/nomacs#247]
Hi,
Please add an option to display additional image information in the title bar
Currently Nomacs display image name and resolution.

My request is to display folder images count, image name, image resolution, image size.
e.g.
1 of 100 - image.png - 1920 x 1080 - 750KB

Also, it be nice if we could edit it with variables, maybe something like this.
{folderCount} - {imageName} - {imageResolution} - {imageSize} - {imageDate} - {zoom} - {RGB}
**But if it would be too hard to add, you can add just the **information above**.**

I Know this information available in the status bar, but usually i don't show the status bar.

Thanks!

**Comment by diemmarkus** [comment]
Hi,

thanks for the suggestion. We won't add additional information to the title bar because it is important in other contexts too (i.e. when switching between windows, connecting to other nomacs instances, ...). Your suggested extensions would add a lot of clutter there. As you mentioned, the statusbar is the place for this information. You can temporarily show the statusbar by holding CTRL & moving the mouse over the image.

best,
markus
