### ISSUE TITLE
Plugin development (comment overlay)

### ISSUE THREAD

**Issue by VINT64** [nomacs/nomacs#280]
Good time of day,

I have been looking for an image viewer with possibility to add overlay over an image.
Having found none, I would like someone to write a plugin for some free image viewer, or to write such plugin on my own.

This kind of overlay is used on anime images' sites like -booru to add translations over the image. When you open an image on the site, it has semi-transparent rectangles over an image. If you hover over a rectangle, a comment will pop-up. 
![comment overlay](https://user-images.githubusercontent.com/33546510/48140146-7891bc00-e2a8-11e8-8abd-c5006a990a86.png)
By single click you can hide/show all these rectangles. Very comfortable to view image.

I would like to use this plugin to provide manga translations to readers. Normally, each user has to buy digital version of manga on his own, but nowadays translators have to edit pages in graphics editor like Paint.NET or Photoshop, and provide 'as is'.
I have an idea to keep translation (or comments, in general) in structured JSON file, and provide a pack of such files to readers, letting them to find the images on their own.

Of course I should provide readers with a program to open these images along with comment files, and instruction, how to install and configure such a program.

I would like to know your opinion on all this, whether this image viewer is suitable for this goal, and any advices which can help me.

Thanks for reading,

**Comment by diemmarkus** [comment]
Hi,

this would be an interesting extension of nomacs. The features can be implemented fairly easy using the nomacs plugin system. You can use the [DkViewportInterface](https://github.com/nomacs/nomacs/blob/004eb0a1b1c6024bc980693053e648c808845d0d/ImageLounge/src/DkCore/DkPluginInterface.h#L161) to overlay the rectangles and a Tooltip to show the translations. [Here](https://github.com/nomacs/nomacs-plugins/tree/master/PaintPlugin) is a plugin that uses the `DkViewportInterface`. Qt supports [JSON](http://doc.qt.io/qt-5/json.html) - so that should also be straight forward.

Please don't hesitate to contact us again, if you have further questions...

best,
markus
