### ISSUE TITLE
Cannot open more than 15 files directly from Explorer (windows file browser)

### ISSUE THREAD

**Issue by Meteor0id** [nomacs/nomacs#323]
**Describe the bug**
I noticed that if I select more than 15 files in Explorer (windows file browser) the context menu no longer contains the option "open". Instead the default action will become "set as background".
This has lead to an unexpected and undesirable result multiple times already: when selecting a number of files and hitting enter, the images are set as a slideshow desktop background, instead of being opened.
Can Nomac please support an arbitrary number of files to be opened in this manner?

**To Reproduce**
1. Select 16 or more files in Window Explorer, of a format which Nomac usually is able to open.
2. Hit enter
3. Good luck recovering your desktop background, the images never opened in Nomac.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1803

**Comment by diemmarkus** [comment]
I didn't know that, thanks! The problem here, is that this is a windows `feature` (not nomacs) - so we can't change it. But, you can change the minimum number of files that trigger this behavior as explained in [this thread](https://winaero.com/blog/windows-10-context-menu-items-missing-when-more-than-15-files-are-selected/). Also, you could open nomacs and drop 15+ files there (nomacs will open tabs for each image selected).

best,
markus
