### ISSUE TITLE
Update source strings in crowdin

### ISSUE THREAD

**Issue by smarquespt** [nomacs/nomacs#33]
Is it possible yo update source strings at crowdin so that we can work on the changes?

**Comment by sfiel** [comment]
done ... but there are only 7 new strings
thank you

**Comment by smarquespt** [comment]
I only requested because I don´t know if there will be a new release soon. If someone could create an issue on this tracker, let´s say 2 weeks before release, we could work on translations with time.

**Comment by sfiel** [comment]
it is always hard for us to tell when there's going to be a release, since it's highly dependent on how much time we can spare for nomacs. We except a new release in the next weeks, but we cannot say exactly when. One problem is also that some new features or bug reports are just introduced or fixed shortly before the release and thus the translation is not available. That was also one reason why we introduced the possibility to update translations.

**Comment by smarquespt** [comment]
Thanks for your explanation. 

Regards
