### ISSUE TITLE
Anti-aliasing and "show pixels if zoom level is above" don't seems to work anymore

### ISSUE THREAD

**Issue by KipThorne** [nomacs/nomacs#335]
As title said, I notice that these two options might have some issues. I tried to disable/activate anti-alias with no visual effect or enhancement (image stays the same). When I set any number in "show pixels if zoom level is above", pixels are always shown, no matter what. Here are two screenshot, first with no zoom level (100%), second with one zoom level (110%). We cleary see some pixels artefacts. These issues wasn't here some times ago and I haven't change any settings.

I tried to uninstall/reinstall, problem is still here. I tried with another PC, same.

I'm on Win10 64bits with Nomacs 3.12.1.4206.
![zoom100](https://user-images.githubusercontent.com/14062442/57968860-8b303080-7970-11e9-8c14-9703df62d622.png)
![zoom110](https://user-images.githubusercontent.com/14062442/57968863-8ec3b780-7970-11e9-8dab-988bad32d1ad.png)

**Comment by qgerman2** [comment]
the same happens on archlinux with nomacs 3.12-5 (artifacts on over 100% zoom), unlike you the 'show pixels if zoom level is above' has never worked for me and i think i've used nomacs for like 6 months, maybe for longer.

**Comment by diemmarkus** [comment]
you are right, thanks for reporting! - this issue was addressed in ae01ab8e4762348a419420830a5e01e4ba2d0ce7 and is fixed in the current beta (left: 3.12, right: 3.13 beta):
![img-2019-05-22 08 48 00](https://user-images.githubusercontent.com/4182443/58153822-58d44b00-7c70-11e9-9ecc-6c2b4b2f9589.png)

best,
markus

p.s.: your test image burnt my eyes (though it's good for testing anti-aliasing : )
