### ISSUE TITLE
New Crop Tool

### ISSUE THREAD

**Issue by diemmarkus** [nomacs/nomacs#345]
create a photoshop-like cropping experience: the crop rectangle will always be aligned to the monitor, while the image is transformed.

since cropping will be re-designed, I am happy if you leave comments/suggestions here.

**Comment by Mintonne** [comment]
**Re: #315**

You mentioned cropping beyond the image border is a feature. Could we kindly have a toggle to disable this?

At the moment, it is very frustrating to use the crop tool. Move the selection slightly over the image border and you will get a white stripe on your image.

**Comment by xbrakl** [comment]
I welcome feature to crop image beyond its original size, but this tool would be better if you can snap cropping tool on borders of original image and you should make some notable push, if you want to crop beyond the borders.

Excelent notable snapping is implemented in Libre office draw. You can there also configure the snapping grid. You could add grid to the background beyond borders of the original image and make posibility to snap cropping tool on the fixed points on the grid and enable snapping only on borders and beyond them.

Example made in Libre Office Draw:

![cropping](https://user-images.githubusercontent.com/25900962/63647992-4a8f4280-c729-11e9-80dd-3015c9a0b0f0.png)

**Comment by xbrakl** [comment]
> 
> 
> create a photoshop-like cropping experience: the crop rectangle will always be aligned to the monitor, while the image is transformed.
> 
> since cropping will be re-designed, I am happy if you leave comments/suggestions here.

Here is the short example of photoshop crop tool for those don't experieced it yet

https://www.youtube.com/watch?v=Ev2w1dkB6lE

**Comment by L--U--P--U--S** [comment]
> There is one more very smart solution. **Make cropping tool to select the whole original image itself at the start of the cropping too**l, so user doesn't have to do it manually. After this you need just to increase or decrease already selected area. (consider this idea as my feature request)

Absolutely support this!

**Comment by diemmarkus** [comment]
- [ ] init
  - [x] select whole image
  - [ ] do not crop beyond the border
  - [ ] new rect if the whole image is selected
  - [ ] adopt rectangle when resizing
  - [ ] zooming does not zoom the rectangle
- [ ] rotation
  - [ ] rotation resets when zoom crosses image fit - add rotation to viewport?
  - [ ] uncontrolled zoom-out if angle is set
  - [ ] adopt rectangle to always be within the image (while rotating)
- [ ] aspect ratio presets
  - [ ] Original
  - [ ] Square
  - [ ] 16:9
  - [ ] 4:3
  - [ ] 3:2
  - [ ] image format
  - [ ] flip to portrait

**Comment by diemmarkus** [comment]
I have been busy with the new crop tool. I would be happy if some of you could try the new version: https://ci.appveyor.com/project/diemmarkus/nomacs/build/artifacts
a few notes:
- crop/cancel buttons are not there yet (you can crop using enter/double click)
- the toolbar is not styled yet

**Comment by L--U--P--U--S** [comment]
Tested the portable version. Good work! Two minor issues:
1. It takes a little time to get used to the change that now one moves the image "behind" the cropping grid, instead of moving the grid in front of the image (as in  version 3.16).
2. After each adjustment of the cropping grid, the image gets zoomed and relocated (centered). Maybe it would be better to stick to the zoom level the image had when entering the cropping tool? Of course, manual zooming should still be allowed (as it is at the moment).

**Comment by Mintonne** [comment]
A few issues I have noticed so far:

1. If the grid goes out of bounds of the image (e.g. after flipping or selecting an aspect ratio), this happens.

![GviM3aFCCG](https://user-images.githubusercontent.com/39894801/89693776-2ae03280-d918-11ea-8f91-2d255b0f4e41.gif)

2. The aspect ratio option doesn't seem to be working correctly. Dragging the mouse offscreen 

![H3snlP9k0S](https://user-images.githubusercontent.com/39894801/89695525-f622aa00-d91c-11ea-87a2-3ef843cf2405.gif)

3. The image jumps around so much due to the aggressive auto zooming. I would personally prefer if the zoom level did not change (similar to Gimp's cropping tool).

4. The rotation value does not reset once you exit crop mode.

---

Even with all the issues, the new crop tool is already so much better than the old one. 👏

**Comment by diemmarkus** [comment]
first off, thanks a lot for testing & the feedback.

>     2\. Maybe it would be better to stick to the zoom level the image had when entering the cropping tool?

the current behavior allows for more fine-grained adjustments if a small portion of an image is to be cropped. note that it is currently not possible to manually zoom the crop rectangle.

another thing, since both of you mentioned the re-centering: during testing, I recognized that interacting with the rectangle is in most cases not needed at all (zoom & pan typically do the trick).

@Mintonne 1+2 and 4 are bugs, thanks!

**Comment by L--U--P--U--S** [comment]
> note that it is currently not possible to manually zoom the crop rectangle.

Yes, clicking the respective tool bar buttons doesn't do anything, but it works via mouse wheel:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1579186/89872619-7ebd7680-dbb9-11ea-97b8-6a31d4a9f9c9.gif)

**Comment by diemmarkus** [comment]
this is intended: the crop rectangle is not zoomed (only the image). getting the zoom buttons etc. working from the toolbar is still missing...
