### ISSUE TITLE
Does nomacs support JPEG 2000 ?

### ISSUE THREAD

**Issue by boxerab** [nomacs/nomacs#35]
If not, are you interested in help with adding in support ?

**Comment by diemmarkus** [comment]
This is currently a windows-only feature. But with nomacs 3 it will be supported on all OS.

**Comment by boxerab** [comment]
Thanks. What library are you using, OpenJPEG? Also, is there a release date for nomacs 3?

**Comment by diemmarkus** [comment]
we were using jasper for jpg2000 but now Qt supports it - so we switched to the qt plugin (which is also using jasper). There is no release date... but we try to release it by the mid/end of November.

**Comment by boxerab** [comment]
Thanks. Frankly, I am surprised people are still using jasper. The project has not been active for a very long time and it has many long-standing bugs  Would you be interested in using OpenJPEG? It has an active community and this year became an official reference implementation for the standard.

**Comment by diemmarkus** [comment]
I know that jasper is not the best choice (actually I fixed 2 bugs for nomacs) - but I like the idea of using the official Qt plugin - since this is usually stable and deploys on every OS we support. 
Have you thought of creating a Qt plugin using OpenJPEG like https://github.com/Code-ReaQtor/libqpsd? This would make things for us (and all people who use Qt) much easier.

**Comment by boxerab** [comment]
Yeah, I was thinking of doing this. Just don't have much time at the moment.
