### ISSUE TITLE
Recent files: bugs and questions

### ISSUE THREAD

**Issue by xbrakl** [nomacs/nomacs#368]
I have few questions about recent files.

1) How to turn off recent files, clear history or set periodical clearage of recent files memory? I would like to clear the recent files history when close the app.

2) Recent files appears at the start of Nomacs. How to turn this off?

Bugs:

3) Bug: "recent files" holds history of folders from which were opened pictures. So I suggest to rename it on "recent folders". This change makes the function more clear for new users.

4) Bug: When I open recent files and hit the big X for the each tab of history and after that reopen recent files or restart Nomacs, this object is not deleted from the history, it will come back on the same place.

![recent](https://user-images.githubusercontent.com/25900962/63649380-1de52600-c73d-11e9-99e1-a04df84e0ce5.png)

**Comment by diemmarkus** [comment]
>     1. How to turn off recent files, clear history or set periodical clearage of recent files memory? I would like to clear the recent files history when close the app.

uncheck ``Edit > Settings > Log Recent Files`` 

>     2\. Recent files appears at the start of Nomacs. How to turn this off?

uncheck ``Edit > Settings > Show Recent Files on Start-up``

>     2\. Bug: When I open recent files and hit the big X for the each tab of history and after that reopen recent files or restart Nomacs, this object is not deleted from the history, it will come back on the same place.

This is unintended behavior which I cannot reproduce here... Can you make sure, that 
- this is the only instance of nomacs currently running
- you do not open images of that folder afterwards

**Comment by xbrakl** [comment]
> 
> 
> > 1. How to turn off recent files, clear history or set periodical clearage of recent files memory? I would like to clear the recent files history when close the app.
> 
> uncheck `Edit > Settings > Log Recent Files`
> 
> > 2. Recent files appears at the start of Nomacs. How to turn this off?
> 
> uncheck `Edit > Settings > Show Recent Files on Start-up`
> 

Thank you for the first 2 answers. That helped. I undestood the first option "Log recent files" as somewhere is created some text log about recent files. Maybe it should be renamed as "remember 'recent files' history". That makes more sense. The second option is fine.

> > 2. Bug: When I open recent files and hit the big X for the each tab of history and after that reopen recent files or restart Nomacs, this object is not deleted from the history, it will come back on the same place.
> 
> This is unintended behavior which I cannot reproduce here... Can you make sure, that
> 
>     * this is the only instance of nomacs currently running
> 
>     * you do not open images of that folder afterwards

I played a little with this bug and you are right. How to reproduce bug:
1) Open some picture (nomacs instance 1). Delete picture from recent files history.
2) Open another Nomacs (instance 2). This instance will show you old history before modification.
3) Close first instance (this will write probably modification to the 'recent files history' log file). Open new instance (history is clear).
4) Close instance 2 (this will overwrite history with file we deleted in first instance from history and history we deleted in first instance is restored if you opens new instance).

This observation tells us, that Nomacs use some sort of buffer and write modifications of recent files history everytime when instance is closed. And new instance loads history from this log file.

I suggest to copy implementation of recent files from some more advanced project like gimp, libre office, inkscape, etc.

I have a question. Does turning off of 'recent files logging' completely turns off this mechanism on the layer of source code? That could mean a little bit faster opening of Nomacs, if user can avoid open/write of log file and allocation of dynamic memory for recent files history.

There are more not so important features in settings, that are active by default. If I could turn off more of them, it could have notable effect on opening speed of Nomacs.

I found there for example:
- check for duplicates on open
- show extra options related to tabs
- loop images

But i don't understand what they does, because the last version of manual, I found is v6 for nomacs 0.2.4 and 0.3.0. Does exist some newer version of manual?

**Comment by diemmarkus** [comment]
> Maybe it should be renamed as "remember 'recent files' history".

I have renamed it, thanks.

> This observation tells us, that Nomacs use some sort of buffer and write modifications of recent files history everytime when instance is closed.

yes, currently there is no syncing between instances. settings are typically saved on close. however, this is not a high priority feature...

>  Does turning off of 'recent files logging' completely turns off this mechanism on the layer of source code?

yes - but: you won't reduce any processing power because we don't write it to the hard disk until the end of the current session (see above)

- check for duplicates on open -> `files are not opened twice in tabs`
- show extra options related to tabs -> `adds options such as First Tab or Go to Tab`
- loop images -> `if you reach the last image in a folder, the first displayed is again...`

note: all options have ToolTips - so if you hover them, more info is displayed. all these options won't change performance. I did address start-up speed on Windows in recent commits (i.e. 1ab901bea05518dffcec554ebeedaaa48e3de43e or 22e6e310edc7a4081942be5d66982959f984658c) with small improvements. However, it appears that creating the UI has become slower with recent Qt versions.

> But i don't understand what they does, because the last version of manual, I found is v6 for nomacs 0.2.4 and 0.3.0. Does exist some newer version of manual?

the problem here is, that we do not have many resources. so I would be very happy if someone (you? : ) would contribute by improving the docs...

**Comment by xbrakl** [comment]
Thank you, that is all, I wanted to know.

**Comment by niruvt** [comment]
> [...] "Log recent files" as somewhere is created some text log about recent files. [...]

@diemmarkus Where is this log saved?

**Comment by neuralgitwork** [comment]
I would also be in need to either know where this log file is saved. Or alternatively, how to clear the recent file list. Because if you uncheck "remember recent files history" the file history is not cleared. And when you uncheck "show recent files on start-up" they are not shown, but check it again, and they are like before... meaning not cleared/deleted.

**Comment by neuralgitwork** [comment]
I would also be in need to know where this log file is saved. Or alternatively, how to clear the recent file list. Because if you uncheck "remember recent files history" the file history is not cleared. And when you uncheck "show recent files on start-up" they are not shown, but check it again, and they are like before... meaning not cleared/deleted.

**Comment by scrubbbbs** [comment]
There is no text log anymore, they are saved in the settings file. A full settings reset is required.

**Comment by blindstitch** [comment]
I was having this same issue (or one closely related to the OP with Nomacs not respecting history states). I think that it is resolved by enabling the log file and flipping the two history options ("Show recent files," "Remember recent files history"). Steps:

1. Enable log file, restart program (issue will persist on load)
2. Toggle both history settings to checked, enabled state; restart
3. Delete most recent item manually
4. Turn history settings back off; restart

After that it seems that the file explorer no longer remembers the previous state.

**Comment by scrubbbbs** [comment]
There were several issues with recents which are fixed in 3.22.0  (36a8970e)
