### ISSUE TITLE
Colors are distorsionated :/

### ISSUE THREAD

**Issue by mortenanakin** [nomacs/nomacs#370]
Hi! Excellent app! I like really much, but have a problem with colors (in picasa viewer colors are ok).
It happens with CMYK images when i export from illustrator/photoshop. I'm a graphic designer, so you have an idea what important this is to me.. Sory for my poor english, i'm from Argentina. Any fix? Maybe i'm missing something. 

![2019-08-28 18 45 27](https://user-images.githubusercontent.com/52761884/63894856-14b9ba80-c9c4-11e9-8196-ffa9b638f1c3.jpg)
![2019-08-28 18 45 43](https://user-images.githubusercontent.com/52761884/63894857-14b9ba80-c9c4-11e9-9d71-0ac99956e169.jpg)

Thanks!

**Comment by diemmarkus** [comment]
hi,
the problem is that Qt (which empowers nomacs) does not support ICC profiles - hence, images stored as cmyk are converted with a very simplified color mapping. so the bad news is: I don't see an improved color mapping in the near future...

best, 
markus

Note for me: color convertion happens in `gjpeghandler.cpp:391`:
````c++
} else if (info->out_color_space == JCS_CMYK) {
	// Convert CMYK->RGB.
	uchar *in = rows[0] + clip.x() * 4;
	QRgb *out = (QRgb*)outImage->scanLine(y);
	for (int i = 0; i < clip.width(); ++i) {
		int k = in[3];
		*out++ = qRgb(k * in[0] / 255, k * in[1] / 255,
					  k * in[2] / 255);
		in += 4;
	}
}
````
