### ISSUE TITLE
Can't navigate among HEIC files

### ISSUE THREAD

**Issue by dandv** [nomacs/nomacs#387]
If I open a directory with HEIC images, I see "<folder name> does not contain any image". However, I can open individual HEIC images. If I try to navigate using the left/right buttons from the toolbar, I get the same error. Curiously, [XnView MP also suffers from the very same issue](https://newsgroup.xnview.com/viewtopic.php?f=62&t=39513&p=158559#p158559).

Using Nomacs 3.8 because I couldn't install [3.12](https://github.com/nomacs/nomacs/issues/308#issuecomment-544831455).

**Comment by diemmarkus** [comment]
this is interesting : ) - it appears that we simply do not have the file filter (*.heic). you can try to open `Tools > Add Image Format`, then drop a `heic` image there.

**Comment by alicektx** [comment]
...are the more 'generic' (desktop-agnostic) mime associations,
for .heic / .heif set correctly there in the first place?
Because most Linux desktops / distros are merely just starting to do so...
Asking because it works fine here with nomacs built from git.

Sample mime config...
[https://github.com/strukturag/libheif/blob/master/gnome/heif.xml](https://github.com/strukturag/libheif/blob/master/gnome/heif.xml)
Installing heif-thumbnailer from struktur AG above 
(aka the main libheif devs themselves), will set such correctly 
(plus, also give you a desktop-agnostic heif thumbnailer obviously)...
[For Ubuntu & derivatives...](https://launchpad.net/~strukturag/+archive/ubuntu/libheif) (file browser might need restarting afterwards).

Markus - a small suggestion: 
add image/heic;image/heif; to the .desktop file...
Such should make things easier for people - well, 
at least when distros / desktops update  their mime databases.

**Comment by diemmarkus** [comment]
> Markus - a small suggestion:
> add image/heic;image/heif; to the .desktop file...
> Such should make things easier for people - well,
> at least when distros / desktops update their mime databases.

thanks, I'll do so...
