### ISSUE TITLE
Dark Theme alternate looks bad

### ISSUE THREAD

**Issue by toefel18** [nomacs/nomacs#474]
**Describe the bug**
When using the dark theme in ubuntu, the meta data info tree view color has too high contrast 

**To Reproduce**
Enable panel metadata info
Enable Dark Theme
Open a photo, and you see this:
![image](https://user-images.githubusercontent.com/11518461/80295260-b3740200-8771-11ea-8030-562868e8efa1.png)

**Expected behavior**
Nicer colors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 20.04

I fixed this myself by adding `alternate-background-color` line to Dark-Theme.css:
```
QTextEdit,
QTreeView,
QTableView,
QListView {
        border: 1px solid #444;
        alternate-background-color:#444;
}

```
Now it looks like this:
![image](https://user-images.githubusercontent.com/11518461/80295264-bf5fc400-8771-11ea-9f1b-665e2c63c857.png)

**Comment by diemmarkus** [comment]
Thanks for the hint and the fix...

**Comment by tjaska** [comment]
For others stumbling here using PopOS:
 
On `Pop!_OS 22.04 LTS` and installing "nomacs" from Pop shop - same problem. That's because it's older version without the fix.

There are 2 versions there: 
- "nomacs" - version 3.12
- "nomacs - Image Lounge" - version  3.16

They seem to be identicalt except the latter one is more recent, so use that.

Thanks @toefel18  for the workaround though. 

If one wants to fix it in the CSS, for PopOS, the Dark-Theme.css could be found in
`usr/share/nomacs/Image%20Lounge/themes/Dark-Theme.css`
