### ISSUE TITLE
Why does nomacs use ctrl+s as "save as"

### ISSUE THREAD

**Issue by ItsDrike** [nomacs/nomacs#492]
In nomacs, when I press <kbd>ctr</kbd>+<kbd>s</kbd> a dialog pops up prompting for the file name and location where I want to save it (a usual "save as" method of saving a file). 

But all I want to do is save the image after rotation (I've used <kbd>r</kbd> to rotate the image) since that won't auto-save the image (well the nomacs will remember it, but any other editor will not). 

So I need to use <kbd>ctr</kbd>+<kbd>s</kbd> to save it so that the image will update.
But this means that I must confirm the overwriting of the file every time (since it uses "save as" rather than "save"). And believe me, that's not what you want when you're working with hundreds of images.

So I have 2 questions:
1. Why does it use <kbd>ctr</kbd>+<kbd>s</kbd> for "save as" functionality rather than just "save" as usual and have a combination like <kbd>ctr</kbd>+<kbd>alt</kbd>+<kbd>s</kbd> for "save as"
2. Why does using <kbd>r</kbd> for rotating doesn't autosave (in most other image editors it does)

**Comment by diemmarkus** [comment]
Hi,

> In nomacs, when I press ctr+s a dialog pops up prompting for the file name and location where I want to save it (a usual "save as" method of saving a file).

nomacs uses <kbd>ctrl</kbd>+<kbd>S</kbd> for `Save` and <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>S</kbd> for `Save As`. However, nomacs will fallback to `Save As` if
- no edits were performed (rotation is not an edit - see below)
- the image format is not supported for writing

> But all I want to do is save the image after rotation (I've used r to rotate the image) since that won't auto-save the image (well the nomacs will remember it, but any other editor will not).

When rotating an image with nomacs, we update the metadata (and auto-save this). This is the best way to perform rotation because it does not need to save the entire image again and it is lossless (i.e. for jpgs). Most editors correctly interpret this flag nowadays (which editor are you using?).

> So I need to use ctr+s to save it so that the image will update.

If you need actual image rotation despite its disadvantages, you can do the following:
- `Edit` > `Settings` > `Advanced`
- Uncheck `Save Exif Orientation`
Now rotations will be an edit operation (without auto-save) - and <kbd>ctrl</kbd>+<kbd>S</kbd> saves the image without asking

**Comment by ItsDrike** [comment]
Thank you for the reply, it makes sense then, I was using `feh` image viewer so I guess it can't read that.

**Comment by ke352802081770314** [comment]
Just wondering, if as described when switching off the "Save Exif Orientation", the rotation is done in the image itself, could you use a lossless transformation of the image data as described in https://www.betterjpeg.com/lossless-rotation.htm ? it seems to me that this would be beneficial, but maybe it is too much a niche to warrant the effort?

**Comment by diemmarkus** [comment]
yes, same goes for cropping. however, our jpg API does not allow for these manipulations...
