### ISSUE TITLE
Open a directory or a photo by keyboard shortcut in File Explorer panel

### ISSUE THREAD

**Issue by sgon00** [nomacs/nomacs#511]
OS: debian 10.

If I enable File Explorer Panel, the side bar will be file explorer panel. 

1. When File Explorer Panel is activated, I use UP/Down key to select a directory which contains some photos. I am unable to open this directory by keyboard so that the right panel will show those photos which are inside the selected directory. I tried many keyboard keys, Enter, Space, Alt+O, +, = \, /, etc.. None of them works. In the end, I have to use the mouse to click on the directory.

2. When File Explorer Panel is activated, I use UP/Down key to select a photo. This is similar issue as the above. I am unable to open this photo by keyboard to the right panel. I tried all the keys, in the end, I have to use mouse.

3. All keyboard shortcuts which work in the right photo panel is not working when the File explorer Panel is activated. This is very annoyed. I would like to use Shift+T, T thumbnails shortcuts. But they are not working unless I click the right panel to activate the right panel. 

4. I can not easily switch (activate) between the left panel and right panel by keyboard shortcuts. I need to keep pressing many times of Tab key to do this. I hope this can be done by something like ctrl + left/right or some other keys.

5. this is the same as another issue I opened, I can not open a photo by keyboard in the right panel when a photo is selected in thumbnail preview mode. I tried Enter key which does not work. I think this feature will be added when that issue is closed. 

Thank you very much for your time and help.

**Comment by ke352802081770314** [comment]
I think the closest analogy to panels would be tabs in a browser, so ctrl-tab would seem an intuitive way for me to switch focus between panels.

**Comment by diemmarkus** [comment]
thanks for the feedback!
1. I have added support to open images with <kbd>ENTER</kbd>. 
2. If you hit <kbd>ENTER</kbd> on a folder, the thumbnail preview will be opened in the right panel. 
3. The file explorer by default heavily uses keyboard shortcuts -> that's why we cannot add nomacs shortcuts here
4. pressing <kbd>TAB</kbd> does the trick (if no other panels are opened)
5. is also working with <kbd>ENTER</kbd>
you can test it [here](https://ci.appveyor.com/project/diemmarkus/nomacs/builds/33891317/artifacts) -> nightly is windows only...
