### ISSUE TITLE
quazip 1.0 breaks shared libraries

### ISSUE THREAD

**Issue by altrupanda** [nomacs/nomacs#568]
**Describe the bug**
nomacs cannot launch once quazip has been updated to 1.0 due to the "Various directories and binary names were finally made consistent."

**To Reproduce**
1. update quazip to 1.0
2. run nomacs in terminal
3. error
`nomacs: error while loading shared libraries: libquazip5.so.1: cannot open shared object file: No such file or directory`

**Desktop (please complete the following information):**
    OS: Arch Linux
    nomacs 3.17.2206-1
    quazip 1.0-1

**Workaround/ bugfix**
This is simply due to a renaming of `libquazip5.so.1` to `libquazip1-qt5.so.1.0` with the quazip 1.0 release. 

A workaround for now is to symlink to the old library with
`ln -s /usr/lib/libquazip1-qt5.so.1.0 /usr/lib/libquazip5.so.1`

**Comment by dvzrv** [comment]
No, this is because you did a partial upgrade. [Partial upgrades are unsupported](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported).

The latest version of nomacs in the repositories is [3.17.2206-2](https://github.com/archlinux/svntogit-community/commit/7d31efa04af0bfda4783b9a2c8b848fa5c5e931a#diff-8d0411b338c83cd8cd8ad9d9db127101) and runs just fine, because it has specifically been rebuilt against quazip 1.0.

This ticket can be closed.
