### ISSUE TITLE
Website down? https://nomacs.org/

### ISSUE THREAD

**Issue by ccoenen** [nomacs/nomacs#814]
**Describe the bug**
Currently, my browser tells me that this website is not available: https://nomacs.org/

**Comment by ingmar** [comment]
Same.

**Comment by taulantxhakli** [comment]
Same for me as well.

**Comment by ingmar** [comment]
Looks like a DNS issue. The nameservers `ns11.prosite.de` and `ns12.prosite.de` aren't answering queries for nomacs.org. Misconfiguration or payment issue?

**Comment by ccoenen** [comment]
it's resolved now [pun absolutely intended]

Thanks everyone!

**Comment by ccoenen** [comment]
hm. Website appears to be down again.

**Comment by ingmar** [comment]
Domain registration expired, serving a placeholder page now.

**Comment by thinrope** [comment]
Fixed for the moment, site is accessible, let's close this issue.

**Comment by Benji377** [comment]
Website (https://nomacs.org/) is down again

**Comment by mmahmoudian** [comment]
We were (and still are) in the process of handling the website and bringing it to Github Pages. It was previously hosted privately and it was not feasible any more. The old website for the time being can be accessed via https://nomacs.cvl.tuwien.ac.at/ and the new website has its own dedicated Github repo in the following address: https://github.com/nomacs/nomacs.github.io which you can see the results in https://nomacs.org/

The goal is to transfer the information of the previous website to the new website and do some changes to the style as well. Sorry for the inconvenience.

I will close this issue since Github Pages are pretty much stable and this issue should not happen any more.
