### ISSUE TITLE
nomacs.org domain has expired

### ISSUE THREAD

**Issue by navinpai** [nomacs/nomacs#880]
**Describe the bug**
https://nomacs.org domain has expired

**To Reproduce**
Visit https://nomacs.org

**Screenshots**
![Screenshot_2022-08-15_15-09-59](https://user-images.githubusercontent.com/408863/184613321-47bc5688-4684-46da-92fc-975a8d6de0c4.png)

**Comment by mmahmoudian** [comment]
It seems some company already nicked it 10 days ago and has parked it:

![image](https://user-images.githubusercontent.com/390889/185981310-2e194648-2daf-4b8a-b527-a70f3baaaab4.png)

![image](https://user-images.githubusercontent.com/390889/185981727-65688658-121f-42c5-b9d1-6db85288fc76.png)

**Comment by novomesk** [comment]
The fact is that we don't have manpower and financial resources to maintain website. I did not have access to it anyway.

Problem is that Windows nomacs can access the domain to check for a new version, I think there was some online help too.

So we will have to make changes in the code not to use the domain which is not in our control.

Nomacs is a large application (I mean there are lot of features), there is lot of work to be done. More volunteers/helpers are needed.

We also don't have digital signature to sign EXE files. When we will make a new release, the installer will not be signed. Digital signature also costs money.

**Comment by LAPIII** [comment]
How much would it be to auto renew the domain? I'm interested in donating money.

**Comment by mmahmoudian** [comment]
I am a maintainer of [Flameshot](https://flameshot.org) and am handing the triage, some of the documentation, website, and some parts of the code and CI. I can help if you want to

**Comment by novomesk** [comment]
Any help is appreciated. Future of nomacs depends on all who are willing to participate on the project.

**Comment by mmahmoudian** [comment]
@novomesk is there a Matrix/IRC/XMPP room that we can get in contact the the devs? Especially @diemmarkus and @sfiel ?

**Comment by novomesk** [comment]
The previous developers no longer participate on developing nomacs.

**Comment by mmahmoudian** [comment]
@novomesk We had the [same situation about Flameshot in 2020](https://github.com/flameshot-org/flameshot/issues/789) and with the small cooperation of the repo owner, we managed to resurrect the project from stale state and get it going. Therefore, the only way to move forward is to have cooperation of the current owners to give (or transfer, which ever they are comfortable with) the Github organization ownership to some trusted party who is willing to be active. Considering the contributions statistics, it is evident that you have recently picked up and handled some of the load. Do you also have some moderation and management access?

**Comment by novomesk** [comment]
I am able to push commits directly and I can also accept Pull Requests of others. My status is Collaborator.

**Comment by mmahmoudian** [comment]
Is it possible to get owners on board for a discussion? There are few things that should be discussed and subsequently done:
1. adding one active owner
2. create a Matrix/XMPP/IRC place to discuss development if needed
3. website and domain
4. potentially adding one triage member (I volunteer for this one)
5. Social media (if it is decided to go with fediverse, e.g Fosstodon.org, I volunteer for this one)

**Comment by novomesk** [comment]
I am very flexible regarding the things to do in future and what communication platform to use. It do not mind continuing if different fork for example. I think the most difficult is the personal problem - to form a team dedicated to the project. Do you have some ideas how to convince potential developers to join us?

**Comment by mmahmoudian** [comment]
I think it is best if we can have @diemmarkus and/or @sfiel onboard and resurrect the project rather than starting a new fork. There is already an organization and everything, so:
1. would be a smoother transition for new, current, and past maintainers
2. would be seamless for distros to keep it in their repo
3. would not damage the public trust

Let's wait for few days and go as usual and see if any of the owners of the repo replies here and we have a dialogue and perhaps set a time for a casual call/group chat

**Comment by LAPIII** [comment]
I see that the domain has been renewed!

**Comment by mmahmoudian** [comment]
can it be related to the following?

![image](https://user-images.githubusercontent.com/390889/186381014-3a3c34cb-c3c8-4f1f-96e0-e59164bfb547.png)

**Comment by novomesk** [comment]
Those are spam comments with social engineering trick to make you to open the URL they sent.

**Comment by mmahmoudian** [comment]
Ok, then I cannot explain the situation. Either the ENOM.COM is doing this for free, or one of the owners of this Github project is in ENOM.COM

Regardless, I'm glad that the website is back. it is an improvement to the situation, but I hope the project gets more traction and see more active development. This is a great project and I would like it to be a successful one.

**Comment by diemmarkus** [comment]
Actually I renewed the domain - sorry for the inconveniences...

**Comment by diemmarkus** [comment]
@mmahmoudian I'm happy to collaborate. Time is the only resource I don't have. If we can setup a call maybe next week?

**Comment by mmahmoudian** [comment]
@diemmarkus Thanks for the response and also the clarification about the domain issue. I know that lack of time is top most reason FLOSS projects are suffering from. I myself am involved with quite a few projects and know the volume of burden.

It would be great if we can have a casual call at some point and have enough interested parties on the call to discuss the contributions and collaborations. I quickly created a Framadate poll to see which time is suitable for whom so that we can maximize the participation:

https://framadate.org/8GX1srpZomM1Rw3g  (valid until 2023-02-20)

**Comment by sfiel** [comment]
Hi, 
I also participated in the poll (thanks @diemmarkus for the heads-up), since I also want to participate to see in which direction nomacs is going. For me it is the same as for @diemmarkus : lack of time and that is why I stopped contributing to nomacs earlier.

**Comment by mmahmoudian** [comment]
I at best can invest some time on triage and community management, as I also have a lot on my plate. To my experience, the most suitable people to keep a project going should have the following features:
1. being passionate enough
2. having recent activity

I took the liberty to [filter the contributions for exactly 2 years](https://github.com/nomacs/nomacs/graphs/contributors?from=2020-08-25&to=2022-08-25&type=c) and the following are the only contributors (ignoring discussion contributions as I don't have time to sieve through them and get some statistics).

![image](https://user-images.githubusercontent.com/390889/186670541-c8f6c997-437b-4486-9118-00803b1e046f.png)

There are also 3 more contributors with open PRs. which their [potential] contribution and definite activeness is not reflected in the graph above. I am deliberately ignoring the type of contribution (translation, code, or etc.). So I would like to tag those that are not yet tagged in this thread for the sake of visibility and possible participation in [the call](https://framadate.org/8GX1srpZomM1Rw3g):

@metalllinux
@VJSchneid 
@MisatoTremor 
@cboxdoerfer 
@pvanek 
@c0xc
@ZTFtrue
@PeterDaveHello

**Comment by masterrite** [comment]
a static website hosted on github might also be a workaround

**Comment by mmahmoudian** [comment]
It seems we have the verdict:

![image](https://user-images.githubusercontent.com/390889/187190961-c41a1aff-0318-4178-b1c1-8937e121a4a9.png)

The public Jitsi room will be in the following URL:

➜ https://talk.snopyta.org/nomacs

In case there is a problem or anything, I can be contacted via [Matrix](https://matrix.to/#/@mehrad:kde.org) or [XMPP](xmpp:mehrad@snopyta.org)

**Comment by PeterDaveHello** [comment]
Sorry that I have very limited bandwidth to join the discussion or do some proactive contribution recently, but just want you know that I saw that I was mentioned in the message, will see if there's any chance that I can do something more in the future.

It's very great to know that something is going on here!

**Comment by diemmarkus** [comment]
> The public Jitsi room will be in the following URL:
> 
> ➜ https://talk.snopyta.org/nomacs
> 
> In case there is a problem or anything, I can be contacted via [Matrix](https://matrix.to/#/@mehrad:kde.org) or [XMPP](xmpp:mehrad@snopyta.org)

@mmahmoudian Stupid me: I didn't notice that times were in UTC. Unfortunately, both (me and @sfiel) cannot make it today at 18:00 UTC. Can we reschedule the meeting for tomorrow same time (Wed 18:00 UTC)?

Really sorry!

**Comment by mmahmoudian** [comment]
> Can we reschedule the meeting for tomorrow same time (Wed 18:00 UTC)?

No worries, it happens. Let's see if @novomesk can participate tomorrow. I believe he should be in the meeting as he is the active person so far in this thread

**Comment by novomesk** [comment]
Hello, I can't join today.

There are 2 point I'd like to discuss (but they could be discussed also without my presence):

1. website, how can we update it in the future.
2. Know-how about translations in nomacs (how it is related to Crowdin, if some credentials are needed, who was responsible for translations, how to update the translations.

**Comment by diemmarkus** [comment]
Sounds good, I'll contact you privately...

**Comment by mmahmoudian** [comment]
@diemmarkus are we going to have the call in 23 minutes?

**Comment by mmahmoudian** [comment]
@diemmarkus fair enough. Let me know if you think I can be of any help

**Comment by novomesk** [comment]
I am able to connect only now. If someone wish to talk with me, I am available.

**Comment by mmahmoudian** [comment]
@novomesk lets have a quick voice call if you are up for it

**Comment by novomesk** [comment]
@diemmarkus Can you write me an email with information about translations? How to update them, so know-how about the whole process.

**Comment by navinpai** [comment]
Good to see this issue sparked a spur of activity in the community :+1:  

Will close this issue now since the website is back up and running! :rocket:

**Comment by novomesk** [comment]
The domain has now different owner probably.

The website was technically abandoned for a long time so the current situation is quite expected.

**Comment by novomesk** [comment]
The site was owned by previous developers (now inactive) and nobody else was able to post any information there since 2020.

**Comment by mmahmoudian** [comment]
@novomesk I don't know what sort of changes has happened since the last time we talked regarding ownership of the project. But I'm willing to help.

**Comment by diemmarkus** [comment]
@novomesk you should have full admin rights of the GitHub page. I don't plan to renew the domain because I had to pay it out of my pocket the last few years. But I'm happy to pass it on.

**Comment by mmahmoudian** [comment]
@diemmarkus I'm willing to pay it off my own pocket. Kinda like donation to this project. I've been doing that for flameshot.org as well for dinner years now. Of course if @novomesk don't want to deal with it, otherwise he have the priority in my mind. Also if any other help is needed, I'm willing to help.

**Comment by diemmarkus** [comment]
That would be great! Now we'd need someone to setup and host (GitHub pages?) the page as well (we were still hosting it at our university, which was already a stretch). Also: can I transfer the domain to you?

**Comment by novomesk** [comment]
@diemmarkus I have rights for https://github.com/nomacs/nomacs only, but not for https://github.com/nomacs

It would be good to have access for Crowdin localizations and AppVeyor for nomacs.

**Comment by mmahmoudian** [comment]
@diemmarkus At Flameshot we had our website's template built as form of contribution/donation from a kind user. Of course we can quickly put something together some website or even use the current website as static html for now just to have something up and running, and eventually move forward a proper website.

@novomesk Do you want to have the domain transferred to you? if not, I can handle the domain and payments. 

In case you two are interested for domain transfer and etc, I would rather communicate in a less public channel since personal information is involved. my matrix @mehrad:kde.org and my email is my github username at gmail.

In case you are stepping down or are reducing your responsibilities, may I suggest giving @novomesk ownership and two others membership of the project so that they can pus the project forward and bring it to a more active state.

**Comment by mmahmoudian** [comment]
@diemmarkus if you are willing to transfer the domain, would you please contact me via Matrix or email to pursue the transfer. The side effect of transfer is that the domain gets extended, which solves the issue of extension. Also it would make the life a lot easier if you can add me as a member to the nomacs organization so that I can create the repo for the Github pages and setup a Github Action to handle the website deployment.

**Comment by diemmarkus** [comment]
Both of you should have an invite for nomacs now. @mmahmoudian I also sent you a PM. Thanks to everyone who keeps supporting nomacs ❤️ .

**Comment by mmahmoudian** [comment]
To update everyone in this thread and for the sake of transparency, here is what we have done so far:
1. domain is getting transferred from @diemmarkus domain register company to my domain register company
2. the data of the previous website exists and we are in process of exporting it from the Wordpress
3. a new repo was created for the (Static Site Generator) SSG: https://github.com/nomacs/nomacs.github.io
4. the plan is to use Zola as SSG with some GitHub Actions for deployment. For now a ready template be used that can accommodate the features we need so that we can quickly have the tutorials and documentation up and running

I personally haven't done front-end web dev for 15 years or so, so the reality is that if someone step up and put together a customized or custom-made Zola theme, I will be more than happy to use an existing theme so that I can be sure that I can pull the updates from them as well (prioritize function over form).

Also, any suggestion/contribution/collaboration is warmly welcome.

**Comment by mmahmoudian** [comment]
> I still don't understand how an expiry can result in the domain hosting an online shop for stereoids which is shady and probably also illegal in many jurisdictions.

I have no idea, and we are waiting for registrars to handle the transfer. What I can guess is that the domain got expired and went into a grace period, then the current registrar "parked" the domain using a service that redirects the traffic.

The website is accessible for now via https://nomacs.cvl.tuwien.ac.at . Whenever the transfer is complete and we gain control over DNS, I will bring up a temp landing page or redirect it to this Github repo.

**Comment by mmahmoudian** [comment]
> May I ask if you have control over that Paypal account that is used for donations? That's also linked to nomacs dot org. It would be a pity if donations went nowhere or who knows where.

No of course I don't. But considering that the Paypal is a separate account compared to the domain and I assume there is also 2FA active, that account should be safe. I think @diemmarkus has control over the Paypal, or at least he definitely knows who has.
